bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: a26yhK0mwNJBEn2iJs+i+7f6Mci3wYFJzkoxm2gBJAUIBBPSrndXgpKVzJ07ytzQDzQNdyhc3MYFZ5oxhpkpFHQnzNqx4PA1WTFyScMhMmdZSUW+yrXL2V3VVNNJ65nUfUiT5lD3/x1sj7E3D7jPG72yAEM4oQ46uRE42zOBeVEyWygeqtIiX8aPZG/kIuAA2PpkFFgszAzGUFTh10q77Fm1KIwoL4Po1/nM1tWPc/2GqF7WlQvzj9JdRf2snilp/StTzRD9M2jKeRWc+YtV2uXwMo450N3R5V2mRlvhM9oU0yAKVXF6OXrgEIkqnVUGoBFecXNSLNHeH8Jizdnr5uh7ttEiEcVa+WtKeBXmS6CCKWCmO4CEQeZ5UQ/HBmrvq6vNIxHWaFv3j8V3FaRvKdcZiViHVZgW8WSjmgQiS8uuQm7LGl44mS3RONCAcgBh2lxRFfg8uqUoptxDRDJFG4OL/o7KiSeP/11DQbHDDTW9Z8ywc0S2Xd1iu6iSTRdcmn7ARqpGzZ1FV7pOYWDxXp/vjkZAa3VonP2IuxGS1P+AvWnXdG8EBR3GeuX0GXOXMuy9yoC0SoCd4FQxL+iK5AFYL64XcudhvHOrC5Ztm2Ou3fqAYU5zweqoWBcPAJxAzDlVjFmJVYOHT1McKcLvYUDatNZ65UXSfz8EkHzOycU=
conda_forge_output_validation: true
